### ISSUE TITLE
Feature Request: Can you open source your docs itself? 

### ISSUE THREAD

**Issue by amiranvarov** [souporserious/mdxts#120]
Hey) as I stated again, pretty cool work you did :) 

I tried to search for the source of the Current docs, I assumed it's in this repo itself, but I couldn't find it. 

Why I'm asking? I assume you built your docs using the MDXTS itself, and it could serve as a great example of production usage. The coolest thing is how it just picks up exported type definitions and comments to them (showed here: https://www.mdxts.dev/packages/mdxts), but I'm a but confused how to set it up in my own docs. Having your own docs as a reference could be very convenient! 

Thanks again!

**Comment by amiranvarov** [comment]
Damn, it was right under my nose, in `site` folder... Phuck.

**Comment by souporserious** [comment]
Glad you were able to find it! I should call this out more 😅 now that v1 is out, I'm shifting focus to writing better docs and templates to showcase how to best use the library.
