### ISSUE TITLE
Build error with custom/private/self-hosted git server

### ISSUE THREAD

**Issue by noxify** [souporserious/mdxts#137]
I'm currently playing around with `mdxts`.

While running the `build` command with the following `next.config.mjs`:

```js
// next.config.mjs

import { createMdxtsPlugin } from 'mdxts/next'

const withMdxts = createMdxtsPlugin({
  theme: 'github-dark',
  siteUrl: 'https://git.<company-host>/<namespace>/documentation',
  gitSource: 'https://git.<company-host>/<namespace>/documentation',
  gitBranch: 'main'
})
/** @type {import('next').NextConfig} */
const nextConfig = {
  eslint: {
    ignoreDuringBuilds: true
  },
  output: "export"
}

export default withMdxts(nextConfig)
```

I get the following error:

```bash
Failed to compile.

./docs/test-file.mdx
Error: test-file.mdx:Error: Git provider not recognized for https://git.<company-host>/<namespace>/documentation
```

Based on the documentation and the related source code:
* https://www.mdxts.dev/packages/components/git-provider
* https://github.com/souporserious/mdxts/blob/main/packages/mdxts/src/components/GitProvider.tsx

it seems that private git repositories are currently not supported.
In our case it's a self-hosted gitlab instance.

## Possible solution

* Add the relevant components to the `mdx-components.tsx` so we can override them
* Add a new prop ( .e.g. `gitProvider` ) to `createMdxtsPlugin` where we can configure the provider ( gitlab / github / bitbucket )
  * this configuration will be checked in the `GitProvider.tsx`
  * if not defined, try to fetch the provider from the url ( current behavior )

**Comment by noxify** [comment]
Repo to test is: https://github.com/noxify/next-mdxts

STRs:

```
git clone git@github.com:noxify/next-mdxts.git
cd next-mdxts
pnpm i
```

Then update the `next.config.mjs` and update the `gitSource` value ( just remove the comments ).
Run `pnpm build` to start the build process.

**Comment by souporserious** [comment]
Appreciate the detailed issue! That error stems from [here](https://github.com/souporserious/mdxts/blob/main/packages/mdxts/src/utils/get-git-file-url.ts) where the git source links are built. To generate the appropriate links in this case would adding a `gitProvider` option to the `next` plugin work for you? That way the utility knows the correct way to construct the link and wouldn't error in this case.

**Comment by noxify** [comment]
> would adding a gitProvider option to the next plugin work for you? 

For me, this would be enough and should cover the most use cases and doesn't introduce any breaking changes.

Alternatively we could just return a generic git icon as fallback or we hide the component if we weren't able to get the git provider from the url.

If you want then I could give it a try to implement the `gitProvider` prop.

**Comment by souporserious** [comment]
Awesome, yeah I'd like to keep the git source a required configuration since it provides a lot of value when navigating around locally and in production. I think the `gitProvider` option makes sense in this case and would be happy to accept a PR!
