### ISSUE TITLE
synthwave-84 bundled theme error

### ISSUE THREAD

**Issue by IGassmann** [souporserious/mdxts#141]
When configuring the MDXTS plugin on Next.js with theme set as `synthwave-84` (one of the Shiki bundled themes), I get a `Error: Cannot read properties of undefined (reading 'border')` when rendering a code block.

I've traced back the error to this code line: https://github.com/souporserious/mdxts/blob/31aff663e66a77419a6b2f7fd0512f1c16ce29f6/packages/mdxts/src/components/CodeInline.tsx#L56

It looks like that either the bundled theme is incomplete or `theme.panel` is incorrectly typed as non-nullish.

**Comment by souporserious** [comment]
Thanks for flagging this! I need to look into what VS Code does and provide fallbacks for these. I've thought about a helper something like `theme('panel.border')`. Still not sure how best to get stronger types though.
