### ISSUE TITLE
allDocs.get requires full pathname?

### ISSUE THREAD

**Issue by capsloq** [souporserious/mdxts#144]
Just followed the get started guide.

mdx-data.ts
```tsx
import { createSource } from 'mdxts'

export const allDocs = createSource('src/content/*.mdx')

console.log("🚀 ~ allDocs.paths():", allDocs.paths())
// 🚀 ~ allDocs.paths(): [ 'coole-namen-fuer-hunde', 'schoene-namen-fuer-huendinnen' ]
```

blog/[slug]/page.tsx
```tsx

export default async function Page({ params }: Props) {
 
  //const doc = await allDocs.get(`/src/content/${params.slug}`) // this does work
  const doc = await allDocs.get(params.slug) // this does not work
```

I was expecting that i don't have to prefix `src/content/`.
Is this a setup error or intentionally?

Thank you

**Comment by capsloq** [comment]
Answering this one myself:
Had to add a baseDirectory to createSource

```tsx
export const allDocs = createSource<{ frontMatter: FrontMatter }>(
  "src/content/*.mdx",
  {
    baseDirectory: "content",
   }
)
 ```
 
 Maybe add to getting started docs, so others can benefit.

**Comment by souporserious** [comment]
Glad you were able to figure it out! Appreciate the feedback, updated the docs [here](https://github.com/souporserious/mdxts/commit/23ae515caa6d004675a0805802acf3af2e34eac0) so it's hopefully more clear that the `baseDirectory` option helps in this situation 😊
