### ISSUE TITLE
Missing slashes in generated `pathname`

### ISSUE THREAD

**Issue by noxify** [souporserious/mdxts#148]
Hi,

I'm currently testing how the handling with sub directory is working and found an unexpected behavior.

Test Repo: https://github.com/noxify/next-mdxts-repro

> The Repo is based on the "custom-git-provider" example - I just updated eslint to v9 with the rules from t3-create-turbo

I have prepared everything, so you can clone the repo and after running `pnpm i` and `pnpm dev` you will see the result also on the startpage.

----

## Test 1

With the following `createSource`

```ts
export const allContentWithoutBaseDir = createSource<{
  frontMatter: FrontMatter
}>("content/**/*.mdx", {
  sort: (a, b) => b.frontMatter.date.getTime() - a.frontMatter.date.getTime(),
})
```

The generated pathnames are 
``` 
/content/content-1/page-1
/content/content-1/page-2
/content/content-1/section/subpage-1
/content/content-1/section/subpage-2
```

## Test 2

With the following `createSource`
```ts
export const allContentWithBaseDir1 = createSource<{
  frontMatter: FrontMatter
}>("content/**/*.mdx", {
  baseDirectory: "content",
  sort: (a, b) => b.frontMatter.date.getTime() - a.frontMatter.date.getTime(),
})
```

The generated pathnames are 
``` 
/content/content-1/section/subpage-2
```

## Test 3

With the following `createSource`
```ts
export const allContentWithBaseDir2 = createSource<{
  frontMatter: FrontMatter
}>("content/**/*.mdx", {
  baseDirectory: "content/", // same result with `/content`
  sort: (a, b) => b.frontMatter.date.getTime() - a.frontMatter.date.getTime(),
})

```

The generated pathnames are 
``` 
/content-1page-1
/content-1page-2
/content-1section/subpage-1
/content-1section/subpage-2
```

----

As you can see, after defining a `baseDirectory` in the `createSource`, the pathnames are wrong / not as expected.

My expected result was: ( based on the result for Test 3 ):

``` 
/content-1/page-1
/content-1/page-2
/content-1/section/subpage-1
/content-1/section/subpage-2
```

----

I have tested it with setting the `basePathname` to `/`, but this results in the same result as shown in "Test 3".
Using `docs/` / `docs`/ `/docs/` doesn't work, too.

----

Question: 
* Is the shown behavior the expected one?
* Is it just user handling and I missed something? 

Thanks!

**Comment by noxify** [comment]
The source for this "issue" is:
https://github.com/souporserious/mdxts/blob/main/packages/mdxts/src/utils/file-path-to-pathname.ts

Added locally the following test to reproduce it:

```ts
// file:
// https://github.com/souporserious/mdxts/blob/main/packages/mdxts/src/utils/file-path-to-pathname.test.ts
  it('reproduces issues #148', () => {
    expect(
      filePathToPathname('content/content_1/section_1/01.page-1.mdx')
    ).toBe('/content/content-1/section-1/page-1')

    expect(
      filePathToPathname(
        'content/content_1/section_1/01.page-1.mdx',
        'content/'
      )
    ).toBe('/content-1/section-1/page-1')
  })
```

**Comment by noxify** [comment]
Possible solution is to use `'/'` ( or `posix.sep`? ) instead of `''` as replace value in 

```ts
    .replace(
      baseDirectory
        ? resolve(process.cwd(), baseDirectoryPath, posix.sep)
        : process.cwd(),
      '/'
    )
```

Ref: https://github.com/souporserious/mdxts/blob/main/packages/mdxts/src/utils/file-path-to-pathname.ts#L45

**Comment by noxify** [comment]
@souporserious - if you want, I can provide a PR with the changes, so we can release it together with #149

**Comment by souporserious** [comment]
Yes, please that'd be great! 🙏

**Comment by noxify** [comment]
Hey @souporserious,

it seems that I had not enough coffee last week and didn't checked the test output correctly.

I assumed adding `/` / `posix.sep` would fix the issue.
But adding it, results in failing the testcase for the following test:
( but my new tests are passing :D )
``` 
// filePathToUrlPathname › uses directory for index and readme
// result is: / 

expect(
      filePathToPathname(
        workingDirectory + '/src/components/index.tsx',
        'components'
      )
    ).toBe('/components')

```

Without the change, all existing testcases are passed, but some of my own testcases are failing.
```
// this fails => result is: /
    expect(
      filePathToPathname('content/content_1/section_1/01.page-1.mdx', 'content')
    ).toBe('/content-1/section-1/page-1')

    // this fails => result is: /content-1section-1/page-1
    expect(
      filePathToPathname(
        'content/content_1/section_1/01.page-1.mdx',
        'content/'
      )
    ).toBe('/content-1/section-1/page-1')

    // this works fine
    expect(
      filePathToPathname('docs/content_1/section_1/01.page-1.mdx', 'docs')
    ).toBe('/content-1/section-1/page-1')

    // this works fine, too
    expect(
      filePathToPathname(
        'src/content/content_1/section_1/01.page-1.mdx',
        'src/content'
      )
    ).toBe('/content-1/section-1/page-1')
```

Currently, I have no idea what's wrong and how to fix it.

* Maybe you have some hints for me?
* Maybe it's not a bug and I just have to think about "How could I structure my repo/code? ( `/src/content` instead of `/content` )

**Comment by souporserious** [comment]
Hm I'm not sure why that specific test fails, but looking at this again and your test cases I _think_ the culprit in the original code is the naive handling of multiple directory names e.g. `content/content_1` and it splits on both causing this issue: 
<img width="324" alt="image" src="https://github.com/souporserious/mdxts/assets/2762082/419183d7-252b-44d1-8333-9440dd8c4911">

Feel free to post a PR and we can work through it together. Appreciate you looking at this!

**Comment by noxify** [comment]
Thanks for the hint - PR is created.
