### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'mdxPath')

### ISSUE THREAD

**Issue by noxify** [souporserious/mdxts#149]
Hi,

I got the following error:

```
Error: Cannot read properties of undefined (reading 'mdxPath')
```

I assumed that I did something wrong and while trying to reproduce the error, I found a very weird behavior.

If you use the following code in the `data.ts`, everything works as expected:

```ts
import { createSource } from "mdxts"

type FrontMatter = {
  title: string
  date: Date
  summary?: string
  tags?: string[]
}

export const allPosts = createSource<{
  frontMatter: FrontMatter
}>("posts/*.mdx", {
  baseDirectory: "posts",
  sort: (a, b) => b.frontMatter.date.getTime() - a.frontMatter.date.getTime(),
})
```

Based on my eslint configuration, I got the following recommendation:
```
Use an `interface` instead of a `type`.eslint[@typescript-eslint/consistent-type-definitions](https://typescript-eslint.io/rules/consistent-type-definitions)
```

Based on this, I updated the `data.ts` to:

```ts
interface FrontMatter {
  title: string
  date: Date
  summary?: string
  tags?: string[]
}

export const allPosts = createSource<{
  frontMatter: FrontMatter
}>("posts/*.mdx", {
  baseDirectory: "posts",
  sort: (a, b) => b.frontMatter.date.getTime() - a.frontMatter.date.getTime(),
})
```

----

Any idea how to fix this? 

if you need a repo to test: https://github.com/noxify/next-mdxts-repro

Thanks!

**Comment by souporserious** [comment]
Thank you for the repro! This is coming from the [`addComputedTypes`](https://github.com/souporserious/tsxmod/blob/main/packages/utils/src/types/addComputedTypes.ts) in tsxmod which powers the type analysis. It was not accounting for interfaces, but I added a fix here https://github.com/souporserious/tsxmod/commit/537efdeb85067e747f2f3194a56b507cb6c92062 which I'll get it out in MDXTS soon!

**Comment by souporserious** [comment]
This has been fixed in version `1.6.0`. Please upgrade and feel free to reopen if the issue persists.

**Comment by noxify** [comment]
Awesome! Thanks @souporserious for fixing it ✌️

**Comment by noxify** [comment]
Have seen that we can now create collections.

Is this the equivalent to https://www.content-collections.dev ?

**Comment by souporserious** [comment]
Collections are an evolution of `createSource`. It does less and focuses mainly on traversing and rendering file system module exports. Still working on docs and an upgrade guide before I deprecate `createSource`, but it's a lot more performant for larger sites since it only ever creates one dynamic import per extension now rather than every file being globbed. Everything is also lazily calculated so things like building API references will be a lot faster.
