### ISSUE TITLE
deprecations

### ISSUE THREAD

**Issue by souporserious** [souporserious/mdxts#40]
Deprecations should be handled throughout the full docs process. For example, adding an `@deprecated` flag in a comment block should show up in any prose content with the version it was introduced and how to upgrade. This should play out through the larger system if applicable like a build/dev process that can also recommend an upgrade path with links to docs if the API is still in use.

**Comment by amiranvarov** [comment]
that's a really good feature tho!

**Comment by souporserious** [comment]
Still planned! Just did some issues cleanup and moved some over to a [roadmap](https://github.com/users/souporserious/projects/2?pane=issue&itemId=64572317) since these were my own feature requests before I made things public 😄
