### ISSUE TITLE
astro integration

### ISSUE THREAD

**Issue by airtonix** [souporserious/mdxts#54]
Hi there, I hope `mdxts` will ensure that it is made in such a way as to allow for integration with other frameworks. 

But first, we're talking about [Astro](https://astro.build/)

- support all output modes, but I want to ensure that static only output works too which means that a requirement of `mode: 'hybrid'` will make this a non starter.
- make sure content source is still completely configurable

**Comment by souporserious** [comment]
Hello, I've split up the package as best possible so some pieces can be integrated with other frameworks where it makes sense. I haven't used Astro personally, but the [utils](https://github.com/souporserious/mdxts/tree/main/packages/mdxts/src/utils) directory would be a good place to start to use the ts-morph utilities which is used for the documentation generation.

As for the components, most are built around Server Components and `use client` which I don't believe Astro supports yet. Although, if Astro can utilize Node APIs some might work ok. I'm hoping to make some of the components isomorphic and not rely on `use client` unless necessary which should help with cross-framework compatibility.

**Comment by souporserious** [comment]
Closing this issue as there will not be first-class support for Astro since they already handle MDX and content collections out of the box which conflict with what this project is aiming to provide for other frameworks like Next.js or Remix that do not have this capabilities.
