### ISSUE TITLE
Theme prop missing during local development 

### ISSUE THREAD

**Issue by leannepepper** [souporserious/mdxts#70]
I've run across an issue during local development where saving a change then immediately navigating in my Next.js app causes the  theme prop for code blocks to throw this error:     
<img width="961" alt="Screenshot 2024-03-01 at 3 51 20 PM" src="https://github.com/souporserious/mdxts/assets/43770359/52c4d90a-25d0-4cc2-8cef-99a0697e315a">

Refreshing the page resolves the error.

**Comment by souporserious** [comment]
Hmm I suspect this is related to using `AsyncLocalStorage` to mimic React Context in Server Components. I'll see if there's any way to fix this, thanks for flagging!
