### ISSUE TITLE
Wrong heading id in production 

### ISSUE THREAD

**Issue by leannepepper** [souporserious/mdxts#71]
I'm not sure what's wrong here but locally headings have the correct id but in production they have a "-2" appended to them:
<img width="271" alt="Screenshot 2024-03-05 at 3 20 06 PM" src="https://github.com/souporserious/mdxts/assets/43770359/48c68227-969d-4ea5-8c44-9008290d6435">

**Comment by souporserious** [comment]
Hm I suspect this is happening in the [remark plugin here](https://github.com/souporserious/mdxts/blob/main/packages/mdxts/src/remark/add-headings.ts#L31) that calculates the heading slugs. It is being reset each time when the plugin runs which is weird why it's adding the suffix 🤔. Does this happen to every heading or only some of them?

**Comment by leannepepper** [comment]
I noticed I had the same title being used in multiple places, making sure they were all unique fixed the issue 😄

**Comment by souporserious** [comment]
Ok cool! This should be documented better how this works. In this case, using the `headings` metadata exported from the module should offer the correct ids used in the content even if there are duplicate titles.
