### ISSUE TITLE
Potential enhancement to `npm create mdxts`: automatically create project?

### ISSUE THREAD

**Issue by dabbott** [souporserious/mdxts#87]
The project looks great! I'm gonna play around with it.

The first thing I tried was running `npm create mdxts` from the website homepage. I got the (appropriate) error message:

```
mdxts: No package.json found. Please run this command in a Next.js project directory.
npm ERR! code 1
npm ERR! path ###
npm ERR! command failed
npm ERR! command sh -c create-mdxts

npm ERR! A complete log of this run can be found in: ###
```

I would typically expect an `npm create` command to set up a new project. I wonder if this command could check for the `package.json` and *if it doesn't exist* offer to create a new project that's fully set up and has an example page or two to show off the various features. That would be super convenient for playing around with the tool, and would match the behavior I expect of a `create`-style setup.

**Comment by souporserious** [comment]
Thanks for trying it out, that's a great suggestion! I need to do a pass on the CLI and add better formatting as well and will definitely add this! I think I can proxy `npm create next-app` in this case with a template pre-configured.
